version: '3'
services:
  web:
    build:
      context: ./web
    container_name: ${CONTAINER_NAME}_php_server
    depends_on:
    - "redis"
    - "db"
    volumes:
      - "../:/var/www/html:Z"
      - "./pgadmin/:/var/www/pgadmin"
      - "./web/sites-enabled:/etc/nginx/sites-enabled"
      - "./web/fpm/php.ini:/etc/php/7.1/fpm/php.ini"
      - "./web/logs:/var/log/nginx"
      - "./source:/root/eden_temp"
      - "./ssh/config:/root/.ssh/config"
      - "./ssh/gitlab_key:/root/gitlab_key"
      - "./web/supervisor-conf:/etc/supervisor/conf.d"
    ports:
      - "${SERVER_PORT}:80"
      - "${SSL_PORT}:443"
      - "${POSTGRES_PGADMIN_PORT}:8080"
    depends_on:
      - "redis"
      - "db"
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${CONTAINER_NAME}_postgres_server
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "postgresdb:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:5432"
  redis:
    container_name: ${CONTAINER_NAME}_redis
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
volumes:
  postgresdb:
