<?php
/**
 * Created by PhpStorm.
 * User: minh.truong
 * Date: 4/30/18
 * Time: 9:53 AM
 */

namespace Packages\General\Config;


interface GeneralConfig
{
    const GENERAL_SYSTEM_CONFIG_PACKAGE = 'FRONTEND_GENERAL';
    const GENERAL_SYSTEM_CONFIG_SITE_URL = 'SITE_URL';
    const GENERAL_SYSTEM_CONFIG_SITE_NAME = 'SITE_NAME';
    const GENERAL_SYSTEM_CONFIG_SITE_LANG = 'SITE_LANG';

    const GENERAL_SYSTEM_CONFIG_SOCIAL_FB = 'SOCIAL_FB';
    const GENERAL_SYSTEM_CONFIG_SOCIAL_TWITTER = 'SOCIAL_TWITTER';
    const GENERAL_SYSTEM_CONFIG_SOCIAL_GOOGLE = 'SOCIAL_GOOGLE';
    const GENERAL_SYSTEM_CONFIG_SOCIAL_ZALO = 'SOCIAL_ZALO';
    const GENERAL_SYSTEM_CONFIG_SOCIAL_PINTEREST = 'SOCIAL_PINTEREST';
    const GENERAL_SYSTEM_CONFIG_SOCIAL_LINKEDIN = 'SOCIAL_LINKEDIN';
    const GENERAL_SYSTEM_CONFIG_SOCIAL_FLICKR = 'SOCIAL_FLICKR';
    const GENERAL_SYSTEM_CONFIG_PHONE = 'PHONE';
    const GENERAL_SYSTEM_CONFIG_SECOND_PHONE = 'SECOND_PHONE';
    const GENERAL_SYSTEM_CONFIG_THIRD_PHONE = 'THIRD_PHONE';
    const GENERAL_SYSTEM_CONFIG_FOUR_PHONE = 'FOUR_PHONE';

    const GENERAL_SYSTEM_CONFIG_COMPANY = 'COMPANY';
    const GENERAL_SYSTEM_CONFIG_WORKING_TIME = 'WORKING_TIME';
    const GENERAL_SYSTEM_CONFIG_ADD1 = 'ADD1';
    const GENERAL_SYSTEM_CONFIG_ADD2 = 'ADD2';
    const GENERAL_SYSTEM_CONFIG_ADD3 = 'ADD3';
    const GENERAL_SYSTEM_CONFIG_ADD4 = 'ADD4';
    const GENERAL_SYSTEM_CONFIG_SKYPE = 'SKYPE';
    const GENERAL_SYSTEM_CONFIG_YOUTUBE = 'YOUTUBE';
    const GENERAL_SYSTEM_CONFIG_EMAIL = 'EMAIL';
    const GENERAL_SYSTEM_CONFIG_EMAIL2 = 'EMAIL2';
    const GENERAL_SYSTEM_CONFIG_EMAIL3 = 'EMAIL3';
    const GENERAL_SYSTEM_CONFIG_EMAIL4 = 'EMAIL4';
}