<?php
namespace Packages\Product\Permissions;

interface Permission
{
    // Access PRODUCT
    const PRODUCT_ACCESS = 'PRODUCT_ACCESS';
    const PRODUCT_CREATE = 'PRODUCT_CREATE';
    const PRODUCT_EDIT = 'PRODUCT_EDIT';
    const PRODUCT_DELETE = 'PRODUCT_DELETE';

    // Category
    const PRODUCT_CATEGORY_ACCESS = 'PRODUCT_CATEGORY_ACCESS';
    const PRODUCT_CATEGORY_CREATE = 'PRODUCT_CATEGORY_CREATE';
    const PRODUCT_CATEGORY_EDIT = 'PRODUCT_CATEGORY_EDIT';
    const PRODUCT_CATEGORY_DELETE = 'PRODUCT_CATEGORY_DELETE';

    // Manufacturer
    const PRODUCT_MANUFACTURER_ACCESS = 'PRODUCT_MANUFACTURER_ACCESS';
    const PRODUCT_MANUFACTURER_CREATE = 'PRODUCT_MANUFACTURER_CREATE';
    const PRODUCT_MANUFACTURER_EDIT = 'PRODUCT_MANUFACTURER_EDIT';
    const PRODUCT_MANUFACTURER_DELETE = 'PRODUCT_MANUFACTURER_DELETE';
}